M48
; DRILL file {KiCad 9.0.4} date 2025-10-09T09:49:21+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-09T09:49:21+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X65.0Y-52.0
X81.28Y-97.028
X136.0Y-119.0
X172.5Y-52.0
X222.0Y-132.0
M30
